# TODO: Service exposing port 8080
apiVersion: v1
kind: Service

metadata:
  name: node-registry-service

spec:
  selector:
    app: node-registry

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: ClusterIP